ARG PHP_IMAGE_TAG
FROM php:${PHP_IMAGE_TAG}

RUN apk add --no-cache $PHPIZE_DEPS

RUN set -ex \
  && apk --no-cache add \
    postgresql-dev

RUN pecl install xdebug \
    && docker-php-ext-install pdo pdo_pgsql \
    && docker-php-ext-enable xdebug

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

WORKDIR /var/html/api

COPY ./api /var/html/api

RUN composer install \
    && composer update